"""creating tables

Revision ID: 47fd7c1cc92e
Revises: 
Create Date: 2021-05-13 23:58:29.361097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fd7c1cc92e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('num_attempts', sa.Integer(), nullable=True),
    sa.Column('sessionEnded', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_lastname'), 'user', ['lastname'], unique=False)
    op.create_index(op.f('ix_user_num_attempts'), 'user', ['num_attempts'], unique=False)
    op.create_index(op.f('ix_user_sessionEnded'), 'user', ['sessionEnded'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attemptNumber', sa.Integer(), nullable=True),
    sa.Column('questionNum', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attemptNumber'), 'quiz', ['attemptNumber'], unique=False)
    op.create_index(op.f('ix_quiz_questionNum'), 'quiz', ['questionNum'], unique=False)
    op.create_index(op.f('ix_quiz_result'), 'quiz', ['result'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionNum', sa.Integer(), nullable=True),
    sa.Column('choice', sa.String(length=64), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_choice'), 'answer', ['choice'], unique=False)
    op.create_index(op.f('ix_answer_questionNum'), 'answer', ['questionNum'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=64), nullable=True),
    sa.Column('correct_choice', sa.String(length=64), nullable=True),
    sa.Column('choice1', sa.String(length=64), nullable=True),
    sa.Column('choice2', sa.String(length=64), nullable=True),
    sa.Column('choice3', sa.String(length=64), nullable=True),
    sa.Column('choice4', sa.String(length=64), nullable=True),
    sa.Column('img', sa.String(length=64), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_choice1'), 'question', ['choice1'], unique=False)
    op.create_index(op.f('ix_question_choice2'), 'question', ['choice2'], unique=False)
    op.create_index(op.f('ix_question_choice3'), 'question', ['choice3'], unique=False)
    op.create_index(op.f('ix_question_choice4'), 'question', ['choice4'], unique=False)
    op.create_index(op.f('ix_question_correct_choice'), 'question', ['correct_choice'], unique=False)
    op.create_index(op.f('ix_question_img'), 'question', ['img'], unique=False)
    op.create_index(op.f('ix_question_question'), 'question', ['question'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_question'), table_name='question')
    op.drop_index(op.f('ix_question_img'), table_name='question')
    op.drop_index(op.f('ix_question_correct_choice'), table_name='question')
    op.drop_index(op.f('ix_question_choice4'), table_name='question')
    op.drop_index(op.f('ix_question_choice3'), table_name='question')
    op.drop_index(op.f('ix_question_choice2'), table_name='question')
    op.drop_index(op.f('ix_question_choice1'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_answer_questionNum'), table_name='answer')
    op.drop_index(op.f('ix_answer_choice'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_quiz_result'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_questionNum'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_attemptNumber'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_sessionEnded'), table_name='user')
    op.drop_index(op.f('ix_user_num_attempts'), table_name='user')
    op.drop_index(op.f('ix_user_lastname'), table_name='user')
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
